<a href="https://colab.research.google.com/github/saswatisamal/PythonWithGenAI/blob/main/price_gouging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Price Gouging](https://www.practiceprobs.com/problemsets/python-pandas/series/price-gouging/)

You suspect your local grocery’s been price gouging the ground beef. You and some friends decide to track the price of ground beef every day for 10 days. You’ve compiled the data into a Series called `beef_prices`, whose index represents the day of each recording.

In [1]:
import numpy as np
import pandas as pd

generator = np.random.default_rng(123)
beef_prices = pd.Series(
    data = np.round(generator.uniform(low=3, high=5, size=10), 2),
    index = generator.choice(10, size=10, replace=False)
)

print(beef_prices)
# 4    4.36
# 8    3.11
# 2    3.44
# 0    3.37
# 6    3.35
# 9    4.62
# 3    4.85
# 5    3.55
# 1    4.64
# 7    4.78
# dtype: float64

4    4.36
8    3.11
2    3.44
0    3.37
6    3.35
9    4.62
3    4.85
5    3.55
1    4.64
7    4.78
dtype: float64


For example, beef was priced 3.37 on the first day, 4.64 on the second day, etc.

Determine which day had the biggest price increase from the prior day.

---

In [17]:
# Sort the Series by index (day)
beef_prices_sorted = beef_prices.sort_index()
#Get the difference from its prev value . If value not present it returns NAN
diff=beef_prices_sorted.diff()
print(diff)
price_on_day_beef_price_max=diff.idxmax()
#day on which price is max
print(price_on_day_beef_price_max)
increased_beef_price_on_day=diff.max()
#Max price
print(increased_beef_price_on_day)



0     NaN
1    1.27
2   -1.20
3    1.41
4   -0.49
5   -0.81
6   -0.20
7    1.43
8   -1.67
9    1.51
dtype: float64
9
1.5100000000000002


## [See our solution!](https://www.practiceprobs.com/problemsets/python-pandas/series/price-gouging/solution/)